#CPack config file
include(InstallRequiredSystemLibraries)
set(CPACK_GENERATOR "")
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VERSION "${${PROJECT_NAME}_VERSION_MAJOR}.${${PROJECT_NAME}_VERSION_MINOR}.${${PROJECT_NAME}_VERSION_PATCH}")
set(CPACK_SOURCE_GENERATOR "TBZ2;ZIP")
set(CPACK_PACKAGE_CONTACT "alexandre.abadie@inria.fr")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${${PROJECT_NAME}_SOURCE_DIR}/cmake/CPack.SerialBlueTermLicense.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A serial and rfcomm communication application based on Qt.")
set(CPACK_RESOURCE_FILE_LICENSE "${${PROJECT_NAME}_SOURCE_DIR}/cmake/CPack.SerialBlueTermLicense.txt")
set(CPACK_RESOURCE_FILE_README "${${PROJECT_NAME}_SOURCE_DIR}/cmake/CPack.SerialBlueTermDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "${${PROJECT_NAME}_SOURCE_DIR}/cmake/CPack.SerialBlueTermWelcome.txt")
set(CPACK_PACKAGE_FILE_NAME "sbterm-${${PROJECT_NAME}_VERSION_MAJOR}.${${PROJECT_NAME}_VERSION_MINOR}.${${PROJECT_NAME}_VERSION_PATCH}")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "sbterm-${${PROJECT_NAME}_VERSION_MAJOR}.${${PROJECT_NAME}_VERSION_MINOR}.${${PROJECT_NAME}_VERSION_PATCH}-src")
  
if(NOT WIN32)
  include(CPackDebConfig)
  include(CPackRpmConfig)
elseif(APPLE)
    set(CPACK_GENERATOR PACKAGEMAKER)
else()
  include(CPackNsisConfig)
endif()

include(CPack)

